import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>FrontEnd Mentor Challenges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <ul className='p-4'>
        <li>
          <Link href='/newbie/nft-preview-card'>NFT Preview Card</Link>
        </li>
      </ul>
    </div>
  )
}
